### ISSUE TITLE
Another metric with the same name already exists.

### ISSUE THREAD

**Issue by laserrapt0r** [aime-team/tf2-benchmarks#1]
Hi! I am getting this error: 

(venv) jetson@jetson-2:~/tf2-benchmarks$ python3 tf2-benchmarks.py --model resnet50 --enable_xla --batch_size 64 --num_gpus 1
2021-10-01 16:20:36.475162: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "tf2-benchmarks.py", line 29, in <module>
    from utils.flags import core as flags_core
  File "/home/jetson/tf2-benchmarks/utils/flags/core.py", line 30, in <module>
    from utils.flags import _base
  File "/home/jetson/tf2-benchmarks/utils/flags/_base.py", line 25, in <module>
    from utils.logs import hooks_helper
  File "/home/jetson/tf2-benchmarks/utils/logs/hooks_helper.py", line 29, in <module>
    from utils.logs import hooks
  File "/home/jetson/tf2-benchmarks/utils/logs/hooks.py", line 28, in <module>
    class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 29, in <module>
    from tensorflow_estimator.python.estimator.canned import optimizers
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/optimizers.py", line 34, in <module>
    'Adagrad': tf.keras.optimizers.Adagrad,
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/keras/optimizer_v2/optimizer_v2.py", line 37, in <module>
    "/tensorflow/api/keras/optimizers", "keras optimizer usage", "method")
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/eager/monitoring.py", line 361, in __init__
    len(labels), name, description, *labels)
  File "/home/jetson/tf2-benchmarks/venv/lib/python3.6/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.

Any idea?

**Comment by kinred** [comment]
The Tensorflow keras .optimizer_v2 has been reorginized in TF 2.6 and later. The optimizer namespace was changed to a compatible one, should work now.
